### PR TITLE
Keep request on error status

### PR DESCRIPTION
**Pull request by geek**

### CODE REVIEW

**Comment by kanongil** [comment]
As far as I can tell this is a breaking change. To make sure that streams are actually closed on errors, a standard `get` would now look something like this (if you don't care about the payload):

```js
Wreck.get('https://google.com/', (err, res, payload) => {
    /* do stuff */
}).on('response', (err, details) => {
    if (err) {
        details.res.abort();
    }
});
```

**Comment by geek** [comment]
@kanongil does this solution solve your needs... now you can get all of the payload details when there is an error status code

**Comment by kanongil** [comment]
No, this solution complicates the api for almost all use cases (compared to v10), including the one in #82.

**Comment by geek** [comment]
@kanongil ok, I'll await your fix.

**Pull request merged**
