### PR TITLE
Wrap error response with Boom

### LINKED ISSUE #82: Option to convert 4xx and 5xx to errors
I'm using Wreck with async to perform a series of network calls. In each function I have to write boilerplate code to check the `response.statusCode` and convert it to a Boom error. If Wreck could do that automatically it would allow me to rewrite something like this:

``` javascript
async.series([
  function(callback) {
    Wreck.get('https://google.com/first', function(err, response, payload) {
      if (err) {
        return callback(err)
      }

      if (response.statusCode >= 400) {
        err = Boom.create(response.statusCode, payload.message)
        return callback(err)
      }

      // do something with first payload
      callback()
    })
  },
  function(callback) {
    Wreck.get('https://google.com/second', function(err, response, payload) {
      if (err) {
        return callback(err)
      }

      if (response.statusCode >= 400) {
        err = Boom.create(response.statusCode, payload.message)
        return callback(err)
      }

      // do something with second payload
      callback()
    })
  },
  function(callback) {
    Wreck.get('https://google.com/third', function(err, response, payload) {
      if (err) {
        return callback(err)
      }

      if (response.statusCode >= 400) {
        err = Boom.create(response.statusCode, payload.message)
        return callback(err)
      }

      // do something  with third payload
      callback()
    })
  }
], function(err) {
  // done
})
```

to this:

``` javascript
var opts = { autoConvertErrors: true }
async.waterfall([
  function(callback) {
    Wreck.get('https://google.com/first', opts, callback)
  },
  function(response, payload, callback) {
    // do something with first payload
    Wreck.get('https://google.com/second', opts, callback)
  },
  function(response, payload, callback) {
    // do something with second payload
    Wreck.get('https://google.com/third', opts, callback)
  },
  function(response, payload, callback) {
    // do something with third payload
    callback()
  }
], function(err) {
  // done
})
```

### PR DESCRIPTION
**Pull request by geek**
Fixes #82

### CODE REVIEW

**Comment by kanongil** [comment]
Sorry, but this is a terrible implementation of the feature.

There are existing use-cases that requires information from the payload on status code errors, which is now impossible to retrieve. Further, all the helper methods don't even provide a way to access any headers.

As it is, something like `h2o2` is not able to upgrade, and will need to find a replacement.

**Comment by AdriVanHoudt** [comment]
@kanongil I agree, would Boom.wrap not be better for this?

**Comment by geek** [comment]
@kanongil and @AdriVanHoudt you have access to the full response object, which is passed as the second argument in the callback. Additionally, the `response` event provides the original request and response objects.

I am open to a better solution if either of you want to submit a PR.

**Comment by kanongil** [comment]
Full access, yes – but it has been aborted. Which means I won't be able to get the payload.

**Comment by kanongil** [comment]
As far as I can tell, this feature can only ever work for the helper methods, and the response behavior needs to be reverted.

**Comment by geek** [comment]
>I am open to a better solution if either of you want to submit a PR.

**Comment by kanongil** [comment]
My PR would just be a revert of this commit. Then you can always create new option for this, as suggested in #82.

**Comment by geek** [comment]
@kanongil doesn't this solve the issue? https://github.com/hapijs/wreck/pull/163

**Pull request merged**
