### PR TITLE
Add a redirected callback request option

### LINKED ISSUE #91: Can't read redirected URI
The current API doesn't allow a user to know which URI that the request might have been redirected to. I need the redirected URI to resolve relative links from the redirected resource.

Another complication, is that I would like to be able to `abort()` the request at any time. The redirection logic means that the `ClientRequest` object returned from `Wreck.request()` will stop working this way once the first redirect is active.

The only simple solution, that can solve both of these issues, is to expose a `redirect` callback, which is called whenever a redirect request has been performed. A signature like this should do the trick: `function (status, location, req) {}`.

Let me know if you agree, and I will take a stab at implementing this.

### PR DESCRIPTION
**Pull request by kanongil**
Fixes #91 as suggested.

### CODE REVIEW

**Comment by geek** [comment]
@kanongil I like this, but what are your thoughts on using the event emitter instead?

```js
self.emit('redirect', statusCode, location, redirectReq);
```

**Comment by AdriVanHoudt** [comment]
since the callback can be called multiple times an event emitter seems more logical

**Comment by kanongil** [comment]
Event emitter on what exactly? The only exposed object is the `ClientRequest` from node.

**Comment by AdriVanHoudt** [comment]
A global one on Wreck doesn't make too much sense and changing stuff around so Wreck.post() returns an object you can listen on seems to big of a change for this(?), if the `res` from the callback is the ClientRequest you might add it to that?

**Comment by kanongil** [comment]
@AdriVanHoudt I would argue that it is very poor style to emit events on objects you don't own.

As far as I can tell, an option callback is the only viable approach.

**Comment by AdriVanHoudt** [comment]
@kanongil I would agree

**Comment by kanongil** [comment]
@geek Are there any other issues?

**Comment by kanongil** [comment]
Ping?

**Comment by geek** [comment]
@kanongil sorry on the delay in getting this in, it looks good.

**Pull request merged**
