### PR TITLE
Fix redirection method for 301, 302

### LINKED ISSUE #138: Redirect 302 changes method from POST to GET
I'm having some problems when following https redirects with wreck.

I have this code:

```
server.ext('onRequest', function (request, reply) {
    Wreck.read(request.raw.req, null, function (err, reqBody) {

      var requestOptions = {
        baseUrl: request.host,
        headers: request.headers,
        redirects: 10,
        beforeRedirect: function (redirectMethod, statusCode, location, resHeaders, redirectOptions, next) {
          console.log('location: ' + location);
          return next();
        },
        timeout: 100000,
        secureProtocol: 'SSLv3_method'
      };

      if(request.method === 'post') {
        requestOptions.payload = reqBody;
      }

      var optionalCallback = function (err, res) {
        return reply(res);
      };

      return Wreck.request(request.method, request.url.href, requestOptions, optionalCallback);

    });
```

It all works fine until I get a `302 Moved Temporarily` which points the request to `https://www.testsite.com/test`.The `location` log above in `beforeRedirect`also prints `https://www.testsite.com/test` but the actual url for the Wreck redirect will be `http://www.testsite.com:443/test` (note that it is still using `http`). This will end up in `socket hangup`.

Am I missing something in my the code or is this a bug in Wreck?

### PR DESCRIPTION
**Pull request by geek**
Fixes #138

### CODE REVIEW

**Comment by kanongil** [comment]
You really should validate that it transmits the `POST` payload again.

**Comment by geek** [comment]
@kanongil in the test?

**Comment by kanongil** [comment]
Yes.

**Comment by geek** [comment]
@kanongil thanks

**Comment by geek** [comment]
Fixed in 780a83d3af216e8cff82e478e874ab28187e0a14

**Pull request merged**
