### PR TITLE
memory leak issue

### PR DESCRIPTION
**Pull request by bodasia**
resolved issue with memory leak on abort request

### CODE REVIEW

**Comment by geek** [comment]
@Bodasia good catch, it might be helpful to add a comment above this line to say a little about its purpose

**Review by geek — APPROVED** [review]

**Review by geek — APPROVED** [review]

**Comment by Bodasia** [comment]
@geek https://github.com/hapijs/wreck/issues/254

**Comment by Bodasia** [comment]
@geek Can you help to fix issue in CI
> Error: ENOENT: no such file or directory, open '/home/travis/build/hapijs/wreck/hapi'

**Comment by geek** [comment]
@Bodasia with help from @cjihrig here is how to fix the issue:

Update the package.json and replace the `lint-md` entry with the following:

```
"lint-md": "eslint --config @hapi/eslint-config-hapi --parser-options=ecmaVersion:8 --rule \"strict: 0, eol-last: 0\" --plugin markdown --ext md .",
```

**Comment by Bodasia** [comment]
@geek thanks

**Comment by hueniverse** [comment]
Thanks!

**Pull request merged**
